# Generated by Django 6.0 on 2026-01-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('Cleaning', 'Cleaning'), ('Painting', 'Painting'), ('Appliance Repair', 'Appliance Repair'), ('Handyman', 'Handyman')], max_length=50),
        ),
    ]
