# Generated by Django 6.0 on 2026-01-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Service availability status'),
        ),
    ]
