# Generated by Django 6.0 on 2026-04-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_alter_reviewrating_options_reviewrating_booking_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
