# Generated by Django 6.0 on 2026-04-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_address_user_phone_number_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, default='', help_text='Company or business name (for service providers)', max_length=200),
        ),
    ]
