# Generated by Django 6.0 on 2026-01-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0002_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('UPI', 'UPI'), ('Net Banking', 'Net Banking'), ('Wallet', 'Wallet')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_received',
            field=models.BooleanField(default=False, help_text='Mark as received by provider'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
