# Generated by Django 6.0 on 2026-01-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0003_booking_payment_method_booking_payment_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=15, null=True),
        ),
    ]
