# Generated by Django 6.0 on 2026-01-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0004_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Esewa', 'Esewa')], default='Cash', max_length=20),
        ),
    ]
