# Generated by Django 6.0 on 2026-01-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0005_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_cancel',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Failed', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Not Available', 'Not Available')], default='Pending', max_length=20),
        ),
    ]
