# Generated by Django 6.0 on 2026-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0006_booking_payment_cancel_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], default='Cash', max_length=20),
        ),
    ]

