# Generated by Django 6.0 on 2026-01-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0008_alter_booking_payment_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_cancel',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Received', 'Received'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Failed', max_length=20),
        ),
    ]

