# Generated by Django 6.0 on 2026-04-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0009_alter_booking_payment_status_choices_add_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Esewa', 'Esewa')], default='Cash', max_length=20),
        ),
    ]
